'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from 'react-redux';
import { store } from '@/store/store';
import {Roboto} from 'next/font/google';
import { ThemeProvider } from '@/context/ThemeContext';
import "./globals.css";

const geistSans = Roboto({
  subsets: ["latin"],
  variable: "--font-Roboto",
  weight: "700",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
  
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased" suppressHydrationWarning >
      <ThemeProvider>
        <Provider store={store}>
          {children}
        </Provider>
        </ThemeProvider>
        </body>
    </html>
  );
}